"""Every figure (vector PDF in report/figures/) and the booktabs table writer.

Style (CLAUDE.md): default matplotlib fonts, bold titles, minimal formatting, light grid at most.
Colours: confirmatory #1F4E79, post-hoc #B35C00, forward test #2E7D32, greys otherwise.
"""
import re

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

import params as P

C, PH, FW = P.COLORS[P.CONFIRMATORY], P.COLORS[P.POSTHOC], P.COLORS[P.FORWARD_TEST]
GREY, LGREY, DGREY = P.COLORS['grey'], P.COLORS['lightgrey'], P.COLORS['darkgrey']

plt.rcParams.update({
    'font.size': 8.5, 'axes.titlesize': 9.5, 'axes.titleweight': 'bold', 'axes.labelsize': 8.5,
    'xtick.labelsize': 8, 'ytick.labelsize': 8, 'legend.fontsize': 7.5, 'legend.frameon': False,
    'axes.spines.top': False, 'axes.spines.right': False, 'axes.grid': True, 'grid.color': '#E6E6E6',
    'grid.linewidth': 0.6, 'axes.axisbelow': True, 'pdf.fonttype': 42, 'lines.linewidth': 1.3,
    'figure.constrained_layout.use': True, 'figure.constrained_layout.h_pad': 0.03, 'figure.constrained_layout.w_pad': 0.03,
})

SIGNAL_LABELS = {'F1': 'F1 openings', 'F2': 'F2 hires', 'F3': 'F3 quits', 'F4': 'F4 layoffs',
                 'F5': 'F5 hours', 'W': 'W wage growth', 'A0': 'A0 composite (prereg.)',
                 'IndMom': 'Industry momentum 12-1'}


def save(fig, name):
    P.FIGS.mkdir(parents=True, exist_ok=True)
    path = P.FIGS / name
    fig.savefig(path)
    plt.close(fig)
    return path


# ---------------------------------------------------------------- tables
def _tex(value):
    text = str(value)
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'), ('_', r'\_'), ('#', r'\#'),
                 ('−', '$-$'), ('±', r'$\pm$'), ('≥', r'$\geq$'), ('≤', r'$\leq$'), ('×', r'$\times$')]:
        text = text.replace(a, b)
    # a minus sign in front of a number is a math minus, not a hyphen (leaves '2004--14' alone)
    return re.sub(r'(?<![\w$-])-(?=\.?\d)', '$-$', text)


def markdown(df, index=True, floatfmt='{:.4g}'):
    """Plain markdown table (no extra dependency)."""
    shown = df.reset_index() if index else df
    cell = lambda v: floatfmt.format(v) if isinstance(v, (float, np.floating)) and not np.isnan(v) else ('' if v is None or (isinstance(v, float) and np.isnan(v)) else str(v))
    rows = ['| ' + ' | '.join(map(str, shown.columns)) + ' |', '|' + '---|' * shown.shape[1]]
    rows += ['| ' + ' | '.join(cell(v) for v in row) + ' |' for row in shown.itertuples(index=False)]
    return '\n'.join(rows)


def write_table(df, name, fmt=None, index=True, align=None, label=None, display=None):
    """CSV (numeric `df`) to analysis/output/tables/<name>.csv; booktabs tabular fragment of `display`
    (default: `df`) to report/tables/<name>.tex. `fmt` maps column -> format string; `label` is the
    result label (CONFIRMATORY / POST-HOC / FORWARD TEST), written as a LaTeX comment."""
    P.TABLES.mkdir(parents=True, exist_ok=True)
    P.TEX.mkdir(parents=True, exist_ok=True)
    df.to_csv(P.TABLES / f'{name}.csv', index=index)
    shown = (display if display is not None else df)
    shown = shown.reset_index() if index else shown.copy()
    fmt = fmt or {}
    for col in shown.columns:
        f = fmt.get(col)
        shown[col] = [('' if (isinstance(v, float) and np.isnan(v)) or v is None else
                       (f.format(v) if f and isinstance(v, (int, float, np.integer, np.floating)) else v))
                      for v in shown[col]]
    align = align or ('l' + 'r' * (shown.shape[1] - 1))
    lines = [f'% {label or ""} | source: analysis/output/tables/{name}.csv (generated by analysis/run.ipynb)',
             rf'\begin{{tabular}}{{{align}}}', r'\toprule',
             ' & '.join(_tex(c) for c in shown.columns) + r' \\', r'\midrule']
    lines += [' & '.join(_tex(v) for v in row) + r' \\' for row in shown.itertuples(index=False)]
    lines += [r'\bottomrule', r'\end{tabular}']
    (P.TEX / f'{name}.tex').write_text('\n'.join(lines) + '\n')
    return P.TEX / f'{name}.tex'


# ---------------------------------------------------------------- D1 single-signal IC
def ic_signals(table):
    """table: index signal, columns mean/se for 'research' and 'test'."""
    order = list(table.index)[::-1]
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.0))
    y = np.arange(len(order))
    for offset, period, colour, marker in [(0.17, 'research', GREY, 'o'), (-0.17, 'test', PH, 's')]:
        m = table.loc[order, f'{period}_ic'].to_numpy()
        e = 2 * table.loc[order, f'{period}_se'].to_numpy()
        ax.errorbar(m, y + offset, xerr=e, fmt=marker, color=colour, ms=4.5, capsize=2, lw=1,
                    label={'research': 'Research 2004–2014', 'test': 'Test 2014–2026'}[period])
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.set_yticks(y, [SIGNAL_LABELS.get(s, s) for s in order])
    ax.set_xlabel('Mean monthly rank IC with next-month relative return (±2 s.e., Newey–West)')
    ax.set_title('Single-signal predictive power: research vs test')
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.16), ncol=2, borderaxespad=0.0)
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_ic_signals.pdf')


# ---------------------------------------------------------------- D2 horizon heatmap
def horizon(ic, t):
    """ic, t: DataFrames signal x horizon."""
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.0))
    limit = np.nanmax(np.abs(ic.to_numpy()))
    image = ax.imshow(ic.to_numpy(), cmap='RdBu_r', vmin=-limit, vmax=limit, aspect='auto')
    for i in range(ic.shape[0]):
        for j in range(ic.shape[1]):
            v, tv = ic.iat[i, j], t.iat[i, j]
            strong = abs(v) > 0.6 * limit
            ax.text(j, i, f'{v:+.3f}\n({tv:+.1f})', ha='center', va='center', fontsize=6.8,
                    color='white' if strong else 'black', fontweight='bold' if abs(tv) >= 2 else 'normal')
    ax.set_xticks(range(ic.shape[1]), [f'{h}m' for h in ic.columns])
    ax.set_yticks(range(ic.shape[0]), [SIGNAL_LABELS.get(s, s) for s in ic.index])
    ax.set_xlabel('Return horizon h (months)')
    ax.set_title('Rank IC by horizon, 2004–2026')
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_visible(False)
    bar = fig.colorbar(image, ax=ax, fraction=0.05, pad=0.03)
    bar.ax.tick_params(labelsize=7)
    bar.set_label('Mean rank IC (t in brackets)', fontsize=7.5)
    return save(fig, 'fig_horizon.pdf')


# ---------------------------------------------------------------- D3 tightness
def timeline(t):
    """t: tightness log(V/U) indexed by earning month."""
    t = t.dropna()
    x = t.index.to_timestamp()
    ts = lambda m: pd.Period(m).to_timestamp()
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.4))
    ax.axvspan(ts('2004-05'), ts('2014-10'), color='#EDEDED', lw=0)
    ax.axvspan(ts('2025-03'), ts('2026-09'), color='#F6E7D8', lw=0)
    ax.axvline(ts('2014-11'), color=DGREY, lw=0.9, ls='--')
    ax.axhline(0, color=GREY, lw=0.8)
    ax.plot(x, t.to_numpy(), color='black', lw=1.2)
    ax.text(ts('2009-07'), 1.05, 'Research period\nMay 2004–Sep 2014', ha='center', va='top', fontsize=7.5)
    ax.text(ts('2017-09'), 1.05, 'Test period, opened once\nNov 2014–Aug 2026', ha='center', va='top', fontsize=7.5)
    ax.text(ts('2025-11'), -1.85, 'last\n18m', ha='center', va='bottom', fontsize=7, color=PH)
    ax.text(ts('2002-08'), 0.05, 'V/U = 1', fontsize=7, color=GREY, va='bottom')
    ax.set_ylim(-2.0, 1.1)
    ax.set_xlim(ts('2002-05'), ts('2026-10'))
    ax.set_ylabel('T = log(V/U)')
    ax.set_title('Labor-market tightness: V/U never exceeded 1 in the research period')
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_timeline.pdf')


def tightness(table):
    """table: index signal; columns rising_ic, rising_se, falling_ic, falling_se, n_rising, n_falling."""
    order = list(table.index)[::-1]
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.9))
    y = np.arange(len(order))
    n_r, n_f = int(table.n_rising.iloc[0]), int(table.n_falling.iloc[0])
    for offset, state, colour, marker in [(0.17, 'rising', PH, 's'), (-0.17, 'falling', GREY, 'o')]:
        m = table.loc[order, f'{state}_ic'].to_numpy()
        e = 2 * table.loc[order, f'{state}_se'].to_numpy()
        label = f'T rising over 12m ({n_r} months)' if state == 'rising' else f'T falling over 12m ({n_f} months)'
        ax.errorbar(m, y + offset, xerr=e, fmt=marker, color=colour, ms=4.5, capsize=2, lw=1, label=label)
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.set_yticks(y, [SIGNAL_LABELS.get(s, s) for s in order])
    ax.set_xlabel('Mean monthly rank IC, 2004–2026 (±2 s.e., Newey–West)')
    ax.set_title('Signal IC when the labor market is tightening vs loosening')
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.16), ncol=2, borderaxespad=0.0)
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_tightness.pdf')


# ---------------------------------------------------------------- D4 cumulative
def cumulative(confirmatory, posthoc):
    """confirmatory/posthoc: dict label -> monthly net excess return Series (test period).
    Primary 'A3' is drawn bold in the confirmatory colour; other confirmatory lines in greys."""
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.9))
    greys = iter([GREY, LGREY, DGREY, '#A6A6A6'])
    styles = iter(['-', '-', '-.', ':'])
    for label, r in confirmatory.items():
        index = (1 + r).cumprod()
        x = r.index.to_timestamp()
        if label.startswith('A3'):
            ax.plot(x, index, color=C, lw=2.0, label=label, zorder=5)
        else:
            ax.plot(x, index, color=next(greys), lw=1.1, ls=next(styles), label=label)
    for label, (r, style) in posthoc.items():
        ax.plot(r.index.to_timestamp(), (1 + r).cumprod(), color=PH, lw=1.5, ls=style, label=label, zorder=4)
    ax.axhline(1, color=DGREY, lw=0.7)
    ax.set_ylabel('Growth of $1 (net excess return)')
    ax.set_title('Test period, Nov 2014–Aug 2026: every preregistered strategy lost money')
    ax.legend(loc='lower left', ncol=2)
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_cumulative.pdf')


# ---------------------------------------------------------------- D5 industry P&L
def industry_pnl(pnl):
    """pnl: Series label -> cumulative contribution (sum of monthly), incl. hedge and costs."""
    pnl = pnl.copy()
    groups = pnl.drop(['Market hedge', 'Trading costs']).sort_values()
    order = list(groups.index) + ['Market hedge', 'Trading costs']
    values = pnl.loc[order]
    fig, ax = plt.subplots(figsize=(P.HALF_WIDTH, 3.5))
    colours = [PH if v < 0 else GREY for v in groups] + [LGREY, LGREY]
    ax.barh(range(len(order)), 100 * values.to_numpy(), color=colours, height=0.7)
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.axhline(len(groups) - 0.5, color=GREY, lw=0.6, ls=':')
    ax.set_yticks(range(len(order)), order)
    ax.invert_yaxis()
    ax.set_xlabel('Cumulative contribution (% points)')
    ax.set_title('A3 P&L by industry, test')
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_industry_pnl.pdf')


# ---------------------------------------------------------------- D6 loadings
def loadings(frame):
    """frame: rows (strategy, factor) with columns coef, se, label (CONFIRMATORY/POST-HOC)."""
    factors = ['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA', 'Mom', 'group_momentum']
    names = {'group_momentum': 'Industry mom.'}
    strategies = list(dict.fromkeys(frame.strategy))
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.7))
    width = 0.8 / len(strategies)
    shades = iter([GREY, LGREY, DGREY])
    markers = iter(['o', 'D', '^', 's', 'v'])
    for i, s in enumerate(strategies):
        sub = frame.loc[frame.strategy == s].set_index('factor').reindex(factors)
        label = sub.label.iloc[0]
        colour = C if s.startswith('A3') else PH if label == P.POSTHOC else next(shades)
        x = np.arange(len(factors)) + (i - (len(strategies) - 1) / 2) * width
        ax.errorbar(x, sub.coef, yerr=2 * sub.se, fmt=next(markers), color=colour, ms=4, capsize=2, lw=1,
                    label=s)
    ax.axhline(0, color=DGREY, lw=0.8)
    ax.set_xticks(range(len(factors)), [names.get(f, f) for f in factors])
    ax.set_ylabel('Loading (±2 s.e., Newey–West)')
    ax.set_title('Factor exposures of the long–short books')
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=len(strategies))
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_loadings.pdf')


# ---------------------------------------------------------------- D7 agent features
def agents_scatter(frame):
    """frame: one row per valid seed-1 candidate with study, research_ic, test_ic (NaN if undefined),
    selected (bool), gated (bool). Undefined test ICs are drawn in a strip below the axis."""
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.3))
    floor = np.floor((np.nanmin(frame.test_ic) - 0.02) * 100) / 100
    for study, marker in [('Sonnet', 'o'), ('Opus', '^')]:
        for gated in [False, True]:
            sub = frame[(frame.study == study) & (frame.gated == gated)]
            y = sub.test_ic.where(sub.test_ic.notna(), floor)
            ax.scatter(sub.research_ic, y, marker=marker, s=24, color=PH if gated else GREY, alpha=0.9, lw=0,
                       label=f'{study}, {"regime-gated" if gated else "ungated"}')
        sel = frame[(frame.study == study) & frame.selected]
        ax.scatter(sel.research_ic, sel.test_ic.where(sel.test_ic.notna(), floor), marker=marker, s=90,
                   facecolors='none', edgecolors='black', lw=1.0)
    ax.scatter([], [], marker='o', s=90, facecolors='none', edgecolors='black', label='selected for A3/A4')
    ax.axhline(0, color=DGREY, lw=0.7)
    ax.axvline(0, color=DGREY, lw=0.7)
    ax.axhline(floor + 0.01, color=GREY, lw=0.6, ls=':')
    ax.set_ylim(floor - 0.01, None)
    ticks = [v for v in ax.get_yticks() if floor + 0.015 < v <= ax.get_ylim()[1]]
    ax.set_yticks(ticks + [floor], [f'{v:+.3f}' if abs(v) > 1e-12 else '0' for v in ticks] + ['undefined*'])
    ax.text(1.01, 0.0, '* feature active in\n   3 or fewer test months', transform=ax.transAxes, ha='left', va='bottom',
            fontsize=6.8, color=DGREY)
    ax.set_xlabel('Research-period mean rank IC')
    ax.set_ylabel('Test-period mean rank IC')
    ax.set_title('Agent-proposed features: research IC did not carry into the test')
    ax.legend(loc='upper left', bbox_to_anchor=(1.01, 1.0), fontsize=7, handletextpad=0.3)
    return save(fig, 'fig_agents_scatter.pdf')


# ---------------------------------------------------------------- D10 agent design diagram
def agents_diagram():
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.6))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 60)
    ax.axis('off')

    def box(x, y, w, h, text, face='white', edge=DGREY, size=7.0, weight='normal', lw=0.9):
        ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle='round,pad=0,rounding_size=1.2', fc=face, ec=edge, lw=lw))
        ax.text(x + w / 2, y + h / 2, text, ha='center', va='center', fontsize=size, fontweight=weight, linespacing=1.25)

    def arrow(a, b, colour=DGREY, ls='-', rad=0.0, both=False):
        ax.add_patch(FancyArrowPatch(a, b, arrowstyle='<|-|>' if both else '-|>', mutation_scale=8, color=colour,
                                     lw=0.9, ls=ls, connectionstyle=f'arc3,rad={rad}', shrinkA=0, shrinkB=0))

    # the two arms
    for x0, title, note in [(1, 'Islands arm: agents share findings', 'reports after proposals 2 and 4 (at most 120 words)'),
                            (53, 'Independent arm: control, no sharing', 'no communication')]:
        box(x0, 37, 46, 21, '', face='#F7F7F7', edge=LGREY)
        ax.text(x0 + 23, 55.6, title, ha='center', va='center', fontsize=7.6, fontweight='bold')
        for i, name in enumerate(['Temporal', 'Composition', 'Interactions']):
            box(x0 + 2 + i * 14.6, 45.5, 12.4, 7, name, face='white', edge=DGREY)
        ax.text(x0 + 23, 42.6, '6 proposals per agent, 3 repetitions', ha='center', va='center', fontsize=6.8, color=DGREY)
        ax.text(x0 + 23, 39.3, note, ha='center', va='center', fontsize=6.8, color=PH if x0 == 1 else DGREY)
    arrow((15.5, 49), (17.5, 49), colour=PH, both=True)
    arrow((30.1, 49), (32.1, 49), colour=PH, both=True)
    # evaluator
    box(31, 21.5, 38, 10, 'Blinded evaluator, research data only\nanonymous variables, groups and months\nfeedback: IC, t-stat, coverage, correlation',
        edge=C, lw=1.1)
    arrow((30, 36.6), (40, 31.9))
    arrow((70, 36.6), (60, 31.9))
    ax.text(50, 34.4, 'proposals in, feedback out', ha='center', va='center', fontsize=6.6, color=DGREY)
    # selection and strategies
    box(31, 3, 38, 10, 'Mechanical selection, repetition 1 only\nt ≥ 1.5, same sign in both halves,\n|corr| < 0.8, at most 3 features per arm',
        edge=C, lw=1.1)
    arrow((50, 21.1), (50, 13.4))
    box(76, 8.5, 22, 7, 'A4 = ridge on F1–F5\n+ island-arm features', face='#EAF0F6', edge=C, size=6.6)
    box(76, 0.5, 22, 7, 'A3 = ridge on F1–F5\n+ independent-arm features', face='#EAF0F6', edge=C, size=6.6)
    arrow((69.4, 9.5), (75.6, 11.5))
    arrow((69.4, 6.5), (75.6, 4.5))
    # judge and human audit
    box(2, 21.5, 23, 10, 'LLM judge: did a later\nproposal use a reported\nclaim?', face='#FBF1E8', edge=PH)
    box(2, 3, 23, 10, 'Human audit of\njudged pairs\n(17 in the Opus study)', edge=PH)
    arrow((13.5, 36.6), (13.5, 31.9), colour=PH)
    arrow((13.5, 21.1), (13.5, 13.4), colour=PH)
    box(76, 21.5, 22, 10, 'Repetitions 2 and 3\nmeasure the search only;\nthey never feed a strategy', edge=LGREY, size=6.6)
    ax.set_title('Blinded agent experiment: two arms with equal budgets')
    return save(fig, 'fig_agents.pdf')


# ---------------------------------------------------------------- Part 3: v2 windows
def v2_windows(frame, a3):
    """frame: index variant, columns = windows (Sharpe). a3: Series window -> Sharpe (confirmatory)."""
    windows = list(frame.columns)
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.8))
    n = len(frame) + 1
    width = 0.8 / n
    shades = ['#B35C00', '#D08A4A', '#E3B48A', '#F1D7BF']
    hatches = ['', '', '//', '..']
    for i, (variant, row) in enumerate(frame.iterrows()):
        x = np.arange(len(windows)) + (i - (n - 1) / 2) * width
        ax.bar(x, row.to_numpy(), width, color=shades[i], edgecolor=PH, lw=0.5, hatch=hatches[i], label=f'{variant} (post-hoc)')
    x = np.arange(len(windows)) + (n - 1 - (n - 1) / 2) * width
    values = [a3.get(w, np.nan) for w in windows]
    ax.bar(x, values, width, color=C, label='A3 primary (confirmatory)')
    for xi, v, w in zip(x, values, windows):
        if np.isnan(v):
            ax.text(xi, 0.02, 'n/a', ha='center', va='bottom', fontsize=6, color=C, rotation=90)
    ax.axhline(0, color=DGREY, lw=0.8)
    ax.set_xticks(range(len(windows)), windows)
    ax.set_ylabel('Annualised net Sharpe ratio')
    ax.set_title('v2 strategies by window, with the preregistered primary for contrast')
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=5, fontsize=7, columnspacing=1.0)
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_v2_windows.pdf')


# ---------------------------------------------------------------- v3 robustness figures (V2d)
def horizon_profile(frame):
    """frame: columns window, h, ic, se, t. Lines per window with ±2 s.e."""
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.9))
    styles = {'research': (GREY, 'o', '--'), 'test': (PH, 's', '-'), 'full': (DGREY, '^', '-')}
    for w, (colour, marker, ls) in styles.items():
        sub = frame[frame.window == w].sort_values('h')
        ax.errorbar(sub.h, sub.ic, yerr=2 * sub.se, fmt=marker, ls=ls, color=colour, ms=4.5, capsize=2, lw=1.1,
                    label={'research': 'Research 2004–2014', 'test': 'Test 2014–2026', 'full': 'Full sample'}[w])
    ax.axhline(0, color=DGREY, lw=0.8)
    ax.set_xticks(sorted(frame.h.unique()))
    ax.set_xlabel('Return horizon h (months)')
    ax.set_ylabel('Mean rank IC of −(hires + quits) (±2 s.e.)')
    ax.set_title('Hiring predicts industry returns slowly: IC of the V2d score by horizon')
    ax.legend(loc='upper left', ncol=3)
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_horizon_profile.pdf')


def v2d_holding(frame):
    """frame: index holding (months), columns windows (Sharpe)."""
    windows = list(frame.columns)
    fig, ax = plt.subplots(figsize=(P.HALF_WIDTH, 2.9))
    n = len(frame)
    width = 0.8 / n
    shades = ['#F1D7BF', '#E3B48A', '#B35C00', '#7A3E00']
    for i, (h, row) in enumerate(frame.iterrows()):
        x = np.arange(len(windows)) + (i - (n - 1) / 2) * width
        ax.bar(x, row.to_numpy(), width, color=shades[i], edgecolor=PH, lw=0.4, label=f'{h} months')
    ax.axhline(0, color=DGREY, lw=0.8)
    short = {'research': 'research', 'test': 'test', 'full': 'full', 'post-2010': 'post-2010', 'last 18m': 'last 18m'}
    ax.set_xticks(range(len(windows)), [short.get(w, w) for w in windows], fontsize=7, rotation=20)
    ax.set_ylabel('Net Sharpe (10 bp)')
    ax.set_title('V2d by holding period')
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.22), ncol=2, fontsize=6.8, title='Holding period', title_fontsize=6.8)
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_v2d_holding.pdf')


def v2d_dropone(frame, baseline):
    """frame: index industry name, columns test_sharpe, full_sharpe. baseline: dict window->V2d Sharpe."""
    frame = frame.sort_values('test_sharpe')
    fig, ax = plt.subplots(figsize=(P.HALF_WIDTH, 3.4))
    y = np.arange(len(frame))
    ax.barh(y + 0.18, frame.test_sharpe, 0.36, color=PH, label='Test')
    ax.barh(y - 0.18, frame.full_sharpe, 0.36, color=LGREY, label='Full sample')
    ax.axvline(baseline['test'], color=PH, lw=0.9, ls='--')
    ax.axvline(baseline['full'], color=GREY, lw=0.9, ls=':')
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.set_yticks(y, frame.index, fontsize=7.5)
    ax.set_xlabel('Net Sharpe, industry removed')
    ax.set_title('V2d: drop one industry')
    ax.set_xlim(0, max(frame.full_sharpe.max(), frame.test_sharpe.max()) * 1.35)
    ax.legend(loc='lower right', fontsize=7, title='dashed: all 13', title_fontsize=6.5)
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_v2d_dropone.pdf')


def v2d_tightness(frame):
    """frame: columns window, regime, sharpe, ic12, ic12_se, n."""
    regimes = ['T rising', 'T falling', 'V/U > 1', 'V/U < 1']
    fig, axes = plt.subplots(1, 2, figsize=(P.FULL_WIDTH, 2.6))
    for ax, metric, label in [(axes[0], 'sharpe', 'Net Sharpe (10 bp)'), (axes[1], 'ic12', 'Mean 12-month rank IC (±2 s.e.)')]:
        x = np.arange(len(regimes))
        for i, (w, colour) in enumerate([('test', PH), ('full', GREY)]):
            sub = frame[frame.window == w].set_index('regime').reindex(regimes)
            err = 2 * sub.ic12_se if metric == 'ic12' else None
            ax.bar(x + (i - 0.5) * 0.38, sub[metric], 0.38, color=colour, yerr=err, capsize=2, ecolor=DGREY, label={'test': 'Test', 'full': 'Full sample'}[w])
            for xi, n in zip(x + (i - 0.5) * 0.38, sub.n):
                ax.text(xi, ax.get_ylim()[0], f'{int(n)}m', ha='center', va='bottom', fontsize=6, color=DGREY)
        ax.axhline(0, color=DGREY, lw=0.8)
        ax.set_xticks(x, regimes, fontsize=7.5)
        ax.set_ylabel(label)
        ax.grid(axis='x', visible=False)
    axes[0].legend(loc='upper left', fontsize=7)
    fig.suptitle('V2d conditional on labor-market tightness at the decision date', fontweight='bold', fontsize=9.5)
    return save(fig, 'fig_v2d_tightness.pdf')
