"""Every figure (vector PDF in report/figures/) and the booktabs table writer.

Style (CLAUDE.md): default matplotlib fonts, bold titles, minimal formatting, light grid at most.
Colours: confirmatory #1F4E79, post-hoc #B35C00, forward test #2E7D32, greys otherwise.
"""
import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

import params as P

C, PH, FW = P.COLORS[P.CONFIRMATORY], P.COLORS[P.POSTHOC], P.COLORS[P.FORWARD_TEST]
GREY, LGREY, DGREY = P.COLORS['grey'], P.COLORS['lightgrey'], P.COLORS['darkgrey']

plt.rcParams.update({
    'font.size': 8.5, 'axes.titlesize': 9.5, 'axes.titleweight': 'bold', 'axes.labelsize': 8.5,
    'xtick.labelsize': 8, 'ytick.labelsize': 8, 'legend.fontsize': 7.5, 'legend.frameon': False,
    'axes.spines.top': False, 'axes.spines.right': False, 'axes.grid': True, 'grid.color': '#E6E6E6',
    'grid.linewidth': 0.6, 'axes.axisbelow': True, 'pdf.fonttype': 42, 'savefig.bbox': 'tight',
    'savefig.pad_inches': 0.03, 'lines.linewidth': 1.3,
})

SIGNAL_LABELS = {'F1': 'F1 openings', 'F2': 'F2 hires', 'F3': 'F3 quits', 'F4': 'F4 layoffs',
                 'F5': 'F5 hours', 'W': 'W wage growth', 'A0': 'A0 composite (prereg.)',
                 'IndMom': 'Industry momentum 12-1'}


def save(fig, name):
    P.FIGS.mkdir(parents=True, exist_ok=True)
    path = P.FIGS / name
    fig.savefig(path)
    plt.close(fig)
    return path


# ---------------------------------------------------------------- tables
def _tex(value):
    text = str(value)
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'), ('_', r'\_'), ('#', r'\#'),
                 ('−', '$-$'), ('±', r'$\pm$'), ('≥', r'$\geq$'), ('≤', r'$\leq$'), ('×', r'$\times$')]:
        text = text.replace(a, b)
    return text


def markdown(df, index=True, floatfmt='{:.4g}'):
    """Plain markdown table (no extra dependency)."""
    shown = df.reset_index() if index else df
    cell = lambda v: floatfmt.format(v) if isinstance(v, (float, np.floating)) and not np.isnan(v) else ('' if v is None or (isinstance(v, float) and np.isnan(v)) else str(v))
    rows = ['| ' + ' | '.join(map(str, shown.columns)) + ' |', '|' + '---|' * shown.shape[1]]
    rows += ['| ' + ' | '.join(cell(v) for v in row) + ' |' for row in shown.itertuples(index=False)]
    return '\n'.join(rows)


def write_table(df, name, fmt=None, index=True, align=None, label=None):
    """CSV to analysis/output/tables/<name>.csv; booktabs tabular fragment to report/tables/<name>.tex.
    `fmt` maps column -> format string (e.g. '{:+.3f}'); `label` is written as a LaTeX comment."""
    P.TABLES.mkdir(parents=True, exist_ok=True)
    P.TEX.mkdir(parents=True, exist_ok=True)
    df.to_csv(P.TABLES / f'{name}.csv', index=index)
    shown = df.reset_index() if index else df.copy()
    fmt = fmt or {}
    for col in shown.columns:
        f = fmt.get(col)
        shown[col] = [('' if (isinstance(v, float) and np.isnan(v)) or v is None else
                       (f.format(v) if f and isinstance(v, (int, float, np.integer, np.floating)) else v))
                      for v in shown[col]]
    align = align or ('l' + 'r' * (shown.shape[1] - 1))
    lines = [f'% {label or name} | source: analysis/output/tables/{name}.csv (generated by analysis/run.ipynb)',
             rf'\begin{{tabular}}{{{align}}}', r'\toprule',
             ' & '.join(_tex(c) for c in shown.columns) + r' \\', r'\midrule']
    lines += [' & '.join(_tex(v) for v in row) + r' \\' for row in shown.itertuples(index=False)]
    lines += [r'\bottomrule', r'\end{tabular}']
    (P.TEX / f'{name}.tex').write_text('\n'.join(lines) + '\n')
    return P.TEX / f'{name}.tex'


# ---------------------------------------------------------------- D1 single-signal IC
def ic_signals(table):
    """table: index signal, columns mean/se for 'research' and 'test'."""
    order = list(table.index)[::-1]
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.0))
    y = np.arange(len(order))
    for offset, period, colour, marker in [(0.17, 'research', GREY, 'o'), (-0.17, 'test', PH, 's')]:
        m = table.loc[order, f'{period}_ic'].to_numpy()
        e = 2 * table.loc[order, f'{period}_se'].to_numpy()
        ax.errorbar(m, y + offset, xerr=e, fmt=marker, color=colour, ms=4.5, capsize=2, lw=1,
                    label={'research': 'Research 2004–2014', 'test': 'Test 2014–2026'}[period])
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.set_yticks(y, [SIGNAL_LABELS.get(s, s) for s in order])
    ax.set_xlabel('Mean monthly rank IC with next-month relative return (±2 s.e., Newey–West)')
    ax.set_title('Single-signal predictive power: research vs test')
    ax.legend(loc='lower right', ncol=2)
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_ic_signals.pdf')


# ---------------------------------------------------------------- D2 horizon heatmap
def horizon(ic, t):
    """ic, t: DataFrames signal x horizon."""
    fig, ax = plt.subplots(figsize=(P.HALF_WIDTH + 0.6, 3.1))
    limit = np.nanmax(np.abs(ic.to_numpy()))
    image = ax.imshow(ic.to_numpy(), cmap='RdBu_r', vmin=-limit, vmax=limit, aspect='auto')
    for i in range(ic.shape[0]):
        for j in range(ic.shape[1]):
            v, tv = ic.iat[i, j], t.iat[i, j]
            strong = abs(v) > 0.6 * limit
            ax.text(j, i, f'{v:+.3f}\n({tv:+.1f})', ha='center', va='center', fontsize=6.8,
                    color='white' if strong else 'black', fontweight='bold' if abs(tv) >= 2 else 'normal')
    ax.set_xticks(range(ic.shape[1]), [f'{h}m' for h in ic.columns])
    ax.set_yticks(range(ic.shape[0]), [SIGNAL_LABELS.get(s, s) for s in ic.index])
    ax.set_xlabel('Return horizon h (months)')
    ax.set_title('Rank IC by horizon, 2004–2026')
    ax.grid(False)
    for spine in ax.spines.values():
        spine.set_visible(False)
    bar = fig.colorbar(image, ax=ax, fraction=0.05, pad=0.03)
    bar.ax.tick_params(labelsize=7)
    bar.set_label('Mean rank IC (t in brackets)', fontsize=7.5)
    return save(fig, 'fig_horizon.pdf')


# ---------------------------------------------------------------- D3 tightness
def timeline(t):
    """t: tightness log(V/U) indexed by earning month."""
    t = t.dropna()
    x = t.index.to_timestamp()
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.3))
    spans = [('2004-05', '2014-09', '#EDEDED', 'Research (selection)'), ('2014-11', '2026-08', 'white', None)]
    ax.axvspan(pd.Period('2004-05').to_timestamp(), pd.Period('2014-10').to_timestamp(), color='#EDEDED', lw=0)
    ax.axvspan(pd.Period('2025-03').to_timestamp(), pd.Period('2026-09').to_timestamp(), color='#F6E7D8', lw=0)
    ax.axvline(pd.Period('2014-11').to_timestamp(), color=DGREY, lw=0.9, ls='--')
    ax.axhline(0, color=GREY, lw=0.8)
    ax.plot(x, t.to_numpy(), color='black', lw=1.2)
    top = t.max() + 0.25
    ax.text(pd.Period('2009-07').to_timestamp(), top, 'Research period\n(May 2004–Sep 2014)', ha='center', va='top', fontsize=7.5)
    ax.text(pd.Period('2020-03').to_timestamp(), top, 'Test period, opened once\n(Nov 2014–Aug 2026)', ha='center', va='top', fontsize=7.5)
    ax.text(pd.Period('2025-11').to_timestamp(), t.min() + 0.05, 'last\n18m', ha='center', va='bottom', fontsize=7, color=PH)
    ax.text(pd.Period('2002-08').to_timestamp(), 0.06, 'V/U = 1', fontsize=7, color=GREY, va='bottom')
    ax.set_ylim(t.min() - 0.15, top + 0.05)
    ax.set_xlim(pd.Period('2002-05').to_timestamp(), pd.Period('2026-10').to_timestamp())
    ax.set_ylabel('T = log(openings / unemployed)')
    ax.set_title('Labor-market tightness never exceeded V/U = 1 in the research period')
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_timeline.pdf')


def tightness(table):
    """table: index signal; columns rising_ic, rising_se, falling_ic, falling_se, n_rising, n_falling."""
    order = list(table.index)[::-1]
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.9))
    y = np.arange(len(order))
    n_r, n_f = int(table.n_rising.iloc[0]), int(table.n_falling.iloc[0])
    for offset, state, colour, marker in [(0.17, 'rising', PH, 's'), (-0.17, 'falling', GREY, 'o')]:
        m = table.loc[order, f'{state}_ic'].to_numpy()
        e = 2 * table.loc[order, f'{state}_se'].to_numpy()
        label = f'T rising over 12m ({n_r} months)' if state == 'rising' else f'T falling over 12m ({n_f} months)'
        ax.errorbar(m, y + offset, xerr=e, fmt=marker, color=colour, ms=4.5, capsize=2, lw=1, label=label)
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.set_yticks(y, [SIGNAL_LABELS.get(s, s) for s in order])
    ax.set_xlabel('Mean monthly rank IC, 2004–2026 (±2 s.e., Newey–West)')
    ax.set_title('Signal IC when the labor market is tightening vs loosening')
    ax.legend(loc='lower right', ncol=2)
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_tightness.pdf')


# ---------------------------------------------------------------- D4 cumulative
def cumulative(confirmatory, posthoc):
    """confirmatory/posthoc: dict label -> monthly net excess return Series (test period).
    Primary 'A3' is drawn bold in the confirmatory colour; other confirmatory lines in greys."""
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.9))
    greys = iter([GREY, LGREY, DGREY, '#A6A6A6'])
    styles = iter(['-', '-', '-.', ':'])
    for label, r in confirmatory.items():
        index = (1 + r).cumprod()
        x = r.index.to_timestamp()
        if label.startswith('A3'):
            ax.plot(x, index, color=C, lw=2.0, label=label, zorder=5)
        else:
            ax.plot(x, index, color=next(greys), lw=1.1, ls=next(styles), label=label)
    for label, (r, style) in posthoc.items():
        ax.plot(r.index.to_timestamp(), (1 + r).cumprod(), color=PH, lw=1.5, ls=style, label=label, zorder=4)
    ax.axhline(1, color=DGREY, lw=0.7)
    ax.set_ylabel('Growth of $1 (net excess return)')
    ax.set_title('Test period, Nov 2014–Aug 2026: every preregistered strategy lost money')
    ax.legend(loc='lower left', ncol=2)
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_cumulative.pdf')


# ---------------------------------------------------------------- D5 industry P&L
def industry_pnl(pnl):
    """pnl: Series label -> cumulative contribution (sum of monthly), incl. hedge and costs."""
    pnl = pnl.copy()
    groups = pnl.drop(['Market hedge', 'Trading costs']).sort_values()
    order = list(groups.index) + ['Market hedge', 'Trading costs']
    values = pnl.loc[order]
    fig, ax = plt.subplots(figsize=(P.HALF_WIDTH, 3.5))
    colours = [PH if v < 0 else GREY for v in groups] + [LGREY, LGREY]
    ax.barh(range(len(order)), 100 * values.to_numpy(), color=colours, height=0.7)
    ax.axvline(0, color=DGREY, lw=0.8)
    ax.axhline(len(groups) - 0.5, color=GREY, lw=0.6, ls=':')
    ax.set_yticks(range(len(order)), order)
    ax.invert_yaxis()
    ax.set_xlabel('Cumulative contribution (% points)')
    ax.set_title('A3 test-period P&L by industry')
    ax.grid(axis='y', visible=False)
    return save(fig, 'fig_industry_pnl.pdf')


# ---------------------------------------------------------------- D6 loadings
def loadings(frame):
    """frame: rows (strategy, factor) with columns coef, se, label (CONFIRMATORY/POST-HOC)."""
    factors = ['Mkt-RF', 'SMB', 'HML', 'RMW', 'CMA', 'Mom', 'group_momentum']
    names = {'group_momentum': 'Industry mom.'}
    strategies = list(dict.fromkeys(frame.strategy))
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.7))
    width = 0.8 / len(strategies)
    shades = iter([GREY, LGREY, DGREY])
    markers = iter(['o', 'D', '^', 's', 'v'])
    for i, s in enumerate(strategies):
        sub = frame.loc[frame.strategy == s].set_index('factor').reindex(factors)
        label = sub.label.iloc[0]
        colour = C if s.startswith('A3') else PH if label == P.POSTHOC else next(shades)
        x = np.arange(len(factors)) + (i - (len(strategies) - 1) / 2) * width
        ax.errorbar(x, sub.coef, yerr=2 * sub.se, fmt=next(markers), color=colour, ms=4, capsize=2, lw=1,
                    label=s)
    ax.axhline(0, color=DGREY, lw=0.8)
    ax.set_xticks(range(len(factors)), [names.get(f, f) for f in factors])
    ax.set_ylabel('Loading (±2 s.e., Newey–West)')
    ax.set_title('Factor exposures of the long–short books')
    ax.legend(loc='upper left', ncol=len(strategies))
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_loadings.pdf')


# ---------------------------------------------------------------- D7 agent features
def agents_scatter(frame):
    """frame: one row per valid seed-1 candidate with study, research_ic, test_ic (NaN if undefined),
    selected (bool), gated (bool)."""
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.2))
    defined = frame.test_ic.notna()
    floor = np.nanmin(frame.test_ic) - 0.022
    for study, marker in [('Sonnet', 'o'), ('Opus', '^')]:
        for gated in [False, True]:
            sub = frame[(frame.study == study) & (frame.gated == gated)]
            y = sub.test_ic.where(sub.test_ic.notna(), floor)
            colour = PH if gated else GREY
            ax.scatter(sub.research_ic, y, marker=marker, s=22, color=colour, alpha=0.85, lw=0,
                       label=f'{study}, {"regime-gated" if gated else "ungated"}')
        sel = frame[(frame.study == study) & frame.selected]
        ax.scatter(sel.research_ic, sel.test_ic.where(sel.test_ic.notna(), floor), marker=marker, s=80,
                   facecolors='none', edgecolors='black', lw=1.0)
    ax.scatter([], [], marker='o', s=80, facecolors='none', edgecolors='black', label='selected for A3/A4')
    ax.axhline(0, color=DGREY, lw=0.7)
    ax.axvline(0, color=DGREY, lw=0.7)
    ax.axhline(floor + 0.011, color=GREY, lw=0.6, ls=':')
    ax.text(ax.get_xlim()[1], floor, 'test IC undefined\n(active ≤ 3 months)', ha='right', va='center', fontsize=6.8, color=DGREY)
    ax.set_xlabel('Research-period mean rank IC')
    ax.set_ylabel('Test-period mean rank IC')
    ax.set_title('Agent-proposed features: research IC did not carry into the test')
    ax.legend(loc='upper left', bbox_to_anchor=(1.01, 1.0), fontsize=7)
    return save(fig, 'fig_agents_scatter.pdf')


# ---------------------------------------------------------------- D10 agent design diagram
def agents_diagram():
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 3.4))
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 54)
    ax.axis('off')

    def box(x, y, w, h, text, face='white', edge=DGREY, size=7.4, weight='normal'):
        ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle='round,pad=0.25,rounding_size=0.8',
                                    fc=face, ec=edge, lw=0.9))
        ax.text(x + w / 2, y + h / 2, text, ha='center', va='center', fontsize=size, fontweight=weight)

    def arrow(a, b, style='-|>', colour=DGREY, ls='-', rad=0.0):
        ax.add_patch(FancyArrowPatch(a, b, arrowstyle=style, mutation_scale=8, color=colour, lw=0.9,
                                     ls=ls, connectionstyle=f'arc3,rad={rad}'))

    # arms
    ax.text(18, 52.5, 'Islands arm (communicating)', ha='center', fontsize=8, fontweight='bold')
    ax.text(57, 52.5, 'Independent arm (control)', ha='center', fontsize=8, fontweight='bold')
    for x0, arm in [(3, 'isl'), (42, 'ind')]:
        for i, name in enumerate(['Temporal', 'Composition', 'Interactions']):
            box(x0 + i * 10.6, 42, 9.2, 7, f'{name}\nagent', face='#F2F2F2')
        ax.text(x0 + 15, 38.6, '6 proposals each  ×  3 repetitions', ha='center', fontsize=6.8, color=DGREY)
    # migration arrows between island agents
    arrow((12.4, 46.8), (13.8, 46.8), style='<|-|>', colour=PH)
    arrow((23.0, 46.8), (24.4, 46.8), style='<|-|>', colour=PH)
    arrow((8, 49.4), (29, 49.4), style='<|-|>', colour=PH, rad=-0.25)
    ax.text(18, 33.6, 'migration reports after proposals 2 and 4\n(≤120 words, findings only)', ha='center',
            fontsize=6.6, color=PH)
    # evaluator
    box(27, 19, 30, 9, 'Blinded evaluator (research data only)\nvariables V01–V06, groups G01–G13, no dates\n'
                      'feedback: IC, t, coverage, correlation', face='white', edge=C, size=6.8)
    arrow((18, 37.5), (35, 28.6))
    arrow((57, 37.5), (49, 28.6))
    arrow((31, 28.6), (12, 37.6), colour=GREY, ls='--', rad=-0.15)
    arrow((53, 28.6), (66, 37.6), colour=GREY, ls='--', rad=0.15)
    # selection and strategies
    box(25, 4, 34, 9, 'Mechanical selection (repetition 1 only)\nt ≥ 1.5, same sign in both halves,\n|corr| < 0.8, at most 3 per arm',
        face='white', edge=C, size=6.8)
    arrow((42, 18.6), (42, 13.6))
    box(64, 9.5, 14, 6, 'A4 = base + island\nfeatures', face='#EAF0F6', edge=C, size=6.8)
    box(64, 1.5, 14, 6, 'A3 = base + independent\nfeatures', face='#EAF0F6', edge=C, size=6.8)
    arrow((59.6, 10.5), (63.6, 12.5))
    arrow((59.6, 6.5), (63.6, 4.5))
    # judge
    box(80, 33, 19, 13, 'LLM judge:\ndid a later proposal\nuse a reported claim?', face='#FBF1E8', edge=PH, size=6.8)
    box(80, 17, 19, 10, 'Human audit\nof 17 judged pairs', face='white', edge=PH, size=6.8)
    arrow((89.5, 32.6), (89.5, 27.6), colour=PH)
    arrow((34, 41.6), (79.6, 39.5), colour=PH, ls=':', rad=-0.12)
    ax.set_title('Blinded agent experiment: two arms with equal budgets', y=1.0)
    return save(fig, 'fig_agents.pdf')


# ---------------------------------------------------------------- Part 3: v2 windows
def v2_windows(frame, a3):
    """frame: index variant, columns = windows (Sharpe). a3: Series window -> Sharpe (confirmatory)."""
    windows = list(frame.columns)
    fig, ax = plt.subplots(figsize=(P.FULL_WIDTH, 2.8))
    n = len(frame) + 1
    width = 0.8 / n
    shades = ['#B35C00', '#D08A4A', '#E3B48A', '#F1D7BF']
    hatches = ['', '', '//', '..']
    for i, (variant, row) in enumerate(frame.iterrows()):
        x = np.arange(len(windows)) + (i - (n - 1) / 2) * width
        ax.bar(x, row.to_numpy(), width, color=shades[i], edgecolor=PH, lw=0.5, hatch=hatches[i], label=f'{variant} (post-hoc)')
    x = np.arange(len(windows)) + (n - 1 - (n - 1) / 2) * width
    values = [a3.get(w, np.nan) for w in windows]
    ax.bar(x, values, width, color=C, label='A3 primary (confirmatory)')
    for xi, v, w in zip(x, values, windows):
        if np.isnan(v):
            ax.text(xi, 0.02, 'n/a', ha='center', va='bottom', fontsize=6, color=C, rotation=90)
    ax.axhline(0, color=DGREY, lw=0.8)
    ax.set_xticks(range(len(windows)), windows)
    ax.set_ylabel('Annualised net Sharpe ratio')
    ax.set_title('v2 strategies by window, with the preregistered primary for contrast')
    ax.legend(loc='upper left', ncol=3, fontsize=7)
    ax.grid(axis='x', visible=False)
    return save(fig, 'fig_v2_windows.pdf')
